trigger:

- master

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            git submodule update --init
            git lfs install
            git lfs pull
            python build.py
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dev/release'
          ArtifactName: 'Windows'
          publishLocation: 'Container'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            call release_runtime.bat
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'EffekseerRuntime150'
          ArtifactName: 'EffekseerRuntime150'
          publishLocation: 'Container'

  - job: MacOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            git submodule update --init
            git lfs install
            git lfs pull
            PACKAGEING_FOR_MAC=1 MONO_SDK_PATH=/Library/Frameworks/Mono.framework/Versions/5_18_1 python3 build.py
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dev/release'
          ArtifactName: 'MacOS'
          publishLocation: 'Container'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dev/Mac'
          ArtifactName: 'MacOS'
          publishLocation: 'Container'
