on: [push, pull_request]
jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Initialize repository
        run: |
         git submodule update --init
         git lfs install
         git lfs pull
      - name: Install packages
        run: sudo apt update && sudo apt install libpulse-dev libglvnd-dev libx11-dev libopenal-dev libvulkan-dev libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libgtk-3-dev ninja-build
      - name: Build
        run: python3 build.py
